/* ==========================================================================
   COLETÂNEA DE MONSTROS — D&D 5e (Lista Genérica)
   Organizada por categoria. Cada entrada possui:
     nome    → nome do monstro
     vidaMax → HP padrão (média dos dados de vida do livro)
     nd      → Nível de Desafio
   ========================================================================== */

const coletaneaMonstros = [

  // ── HUMANOIDES ──────────────────────────────────────────────────────────
  { nome: "Goblin",             vidaMax: 7,   nd: "1/4" },
  { nome: "Kobold",             vidaMax: 5,   nd: "1/8" },
  { nome: "Hobgoblin",          vidaMax: 11,  nd: "1/2" },
  { nome: "Orc",                vidaMax: 15,  nd: "1/2" },
  { nome: "Gnoll",              vidaMax: 22,  nd: "1/2" },
  { nome: "Bugbear",            vidaMax: 27,  nd: "1"   },
  { nome: "Lizardfolk",         vidaMax: 22,  nd: "1/2" },
  { nome: "Troglodita",         vidaMax: 13,  nd: "1/4" },
  { nome: "Bandido",            vidaMax: 11,  nd: "1/8" },
  { nome: "Capitão Bandido",    vidaMax: 65,  nd: "2"   },
  { nome: "Guarda",             vidaMax: 11,  nd: "1/8" },
  { nome: "Veterano",           vidaMax: 58,  nd: "3"   },
  { nome: "Berserker",          vidaMax: 67,  nd: "2"   },
  { nome: "Cultista",           vidaMax: 9,   nd: "1/8" },
  { nome: "Fanático Cultista",  vidaMax: 33,  nd: "2"   },

  // ── MORTOS-VIVOS ─────────────────────────────────────────────────────────
  { nome: "Esqueleto",          vidaMax: 13,  nd: "1/4" },
  { nome: "Zumbi",              vidaMax: 22,  nd: "1/4" },
  { nome: "Ghoul",              vidaMax: 22,  nd: "1"   },
  { nome: "Sombra",             vidaMax: 16,  nd: "1/2" },
  { nome: "Espectro",           vidaMax: 22,  nd: "1"   },
  { nome: "Fantasma",           vidaMax: 45,  nd: "4"   },
  { nome: "Múmia",              vidaMax: 58,  nd: "3"   },
  { nome: "Senhor Múmia",       vidaMax: 97,  nd: "15"  },
  { nome: "Vampiro Spawn",      vidaMax: 82,  nd: "5"   },
  { nome: "Vampiro",            vidaMax: 144, nd: "13"  },
  { nome: "Lich",               vidaMax: 135, nd: "21"  },
  { nome: "Banshee",            vidaMax: 58,  nd: "4"   },
  { nome: "Morto-Vivo Carcaça", vidaMax: 45,  nd: "3"   },
  { nome: "Wight",              vidaMax: 45,  nd: "3"   },
  { nome: "Wraith",             vidaMax: 67,  nd: "5"   },

  // ── BESTAS ───────────────────────────────────────────────────────────────
  { nome: "Rato Gigante",       vidaMax: 7,   nd: "1/8" },
  { nome: "Morcego Gigante",    vidaMax: 22,  nd: "1/4" },
  { nome: "Aranha Gigante",     vidaMax: 26,  nd: "1"   },
  { nome: "Lobo",               vidaMax: 11,  nd: "1/4" },
  { nome: "Lobo Gigante",       vidaMax: 37,  nd: "1"   },
  { nome: "Urso Pardo",         vidaMax: 34,  nd: "1"   },
  { nome: "Urso Polar Gigante", vidaMax: 42,  nd: "2"   },
  { nome: "Crocodilo",          vidaMax: 19,  nd: "1/2" },
  { nome: "Crocodilo Gigante",  vidaMax: 85,  nd: "5"   },
  { nome: "Escorpião Gigante",  vidaMax: 52,  nd: "3"   },
  { nome: "Tubarão Gigante",    vidaMax: 126, nd: "5"   },
  { nome: "Pantera",            vidaMax: 13,  nd: "1/4" },
  { nome: "Tigre",              vidaMax: 37,  nd: "1"   },
  { nome: "Leão",               vidaMax: 26,  nd: "1"   },
  { nome: "Mamute",             vidaMax: 126, nd: "6"   },

  // ── CRIATURAS MÁGICAS & MONSTRUOSIDADES ──────────────────────────────────
  { nome: "Grifo",              vidaMax: 59,  nd: "2"   },
  { nome: "Hipogrifo",          vidaMax: 38,  nd: "1"   },
  { nome: "Peryton",            vidaMax: 33,  nd: "2"   },
  { nome: "Quimera",            vidaMax: 114, nd: "6"   },
  { nome: "Basilisco",          vidaMax: 52,  nd: "3"   },
  { nome: "Medusa",             vidaMax: 127, nd: "6"   },
  { nome: "Minotauro",          vidaMax: 76,  nd: "3"   },
  { nome: "Centauro",           vidaMax: 45,  nd: "2"   },
  { nome: "Ciclope",            vidaMax: 138, nd: "6"   },
  { nome: "Harpia",             vidaMax: 38,  nd: "1"   },
  { nome: "Hidra",              vidaMax: 172, nd: "8"   },
  { nome: "Mantícora",          vidaMax: 68,  nd: "3"   },
  { nome: "Worg",               vidaMax: 26,  nd: "1/2" },
  { nome: "Troll",              vidaMax: 84,  nd: "5"   },
  { nome: "Ogro",               vidaMax: 59,  nd: "2"   },
  { nome: "Gigante da Colina",  vidaMax: 105, nd: "5"   },
  { nome: "Gigante de Pedra",   vidaMax: 126, nd: "7"   },
  { nome: "Gigante do Gelo",    vidaMax: 138, nd: "9"   },
  { nome: "Gigante do Fogo",    vidaMax: 162, nd: "9"   },
  { nome: "Gigante das Nuvens", vidaMax: 200, nd: "9"   },
  { nome: "Gigante da Tempestade", vidaMax: 230, nd: "13" },

  // ── ELEMENTAIS ───────────────────────────────────────────────────────────
  { nome: "Elemental do Ar",    vidaMax: 90,  nd: "5"   },
  { nome: "Elemental da Terra", vidaMax: 126, nd: "5"   },
  { nome: "Elemental do Fogo",  vidaMax: 102, nd: "5"   },
  { nome: "Elemental da Água",  vidaMax: 114, nd: "5"   },
  { nome: "Mefito de Lama",     vidaMax: 27,  nd: "1/4" },
  { nome: "Mefito de Fumaça",   vidaMax: 22,  nd: "1/4" },
  { nome: "Mefito de Vapor",    vidaMax: 22,  nd: "1/4" },
  { nome: "Salamandra",         vidaMax: 114, nd: "5"   },
  { nome: "Djinn",              vidaMax: 161, nd: "11"  },
  { nome: "Efreet",             vidaMax: 200, nd: "11"  },

  // ── CONSTRUCTOS ──────────────────────────────────────────────────────────
  { nome: "Homúnculo",          vidaMax: 5,   nd: "0"   },
  { nome: "Estátua Animada",    vidaMax: 33,  nd: "2"   },
  { nome: "Golem de Argila",    vidaMax: 133, nd: "9"   },
  { nome: "Golem de Pedra",     vidaMax: 178, nd: "10"  },
  { nome: "Golem de Ferro",     vidaMax: 210, nd: "16"  },
  { nome: "Golem de Carne",     vidaMax: 93,  nd: "5"   },
  { nome: "Escudo Guardião",    vidaMax: 52,  nd: "7"   },

  // ── FERAS DRACÔNICAS ─────────────────────────────────────────────────────
  { nome: "Dragão Filhote Branco",  vidaMax: 32,  nd: "2"  },
  { nome: "Dragão Filhote Preto",   vidaMax: 33,  nd: "2"  },
  { nome: "Dragão Filhote Verde",   vidaMax: 38,  nd: "2"  },
  { nome: "Dragão Filhote Azul",    vidaMax: 52,  nd: "3"  },
  { nome: "Dragão Filhote Vermelho",vidaMax: 75,  nd: "4"  },
  { nome: "Dragão Jovem Branco",    vidaMax: 133, nd: "6"  },
  { nome: "Dragão Jovem Preto",     vidaMax: 127, nd: "7"  },
  { nome: "Dragão Jovem Verde",     vidaMax: 136, nd: "8"  },
  { nome: "Dragão Jovem Azul",      vidaMax: 152, nd: "9"  },
  { nome: "Dragão Jovem Vermelho",  vidaMax: 178, nd: "10" },
  { nome: "Dragão Adulto Branco",   vidaMax: 200, nd: "13" },
  { nome: "Dragão Adulto Preto",    vidaMax: 195, nd: "14" },
  { nome: "Dragão Adulto Verde",    vidaMax: 207, nd: "15" },
  { nome: "Dragão Adulto Azul",     vidaMax: 225, nd: "16" },
  { nome: "Dragão Adulto Vermelho", vidaMax: 256, nd: "17" },
  { nome: "Dragão Ancião Branco",   vidaMax: 333, nd: "20" },
  { nome: "Dragão Ancião Vermelho", vidaMax: 546, nd: "24" },
  { nome: "Dragão Ancião Azul",     vidaMax: 481, nd: "23" },
  { nome: "Wyvern",                 vidaMax: 110, nd: "6"  },
  { nome: "Pseudodragão",           vidaMax: 7,   nd: "1/4"},

  // ── ABERRAÇÕES ───────────────────────────────────────────────────────────
  { nome: "Abissal",            vidaMax: 50,  nd: "2"   },
  { nome: "Mind Flayer",        vidaMax: 71,  nd: "7"   },
  { nome: "Beholder",           vidaMax: 180, nd: "13"  },
  { nome: "Beholder Zumbi",     vidaMax: 93,  nd: "5"   },
  { nome: "Chuul",              vidaMax: 93,  nd: "4"   },
  { nome: "Aboleth",            vidaMax: 135, nd: "10"  },
  { nome: "Gibbering Mouther",  vidaMax: 67,  nd: "2"   },
  { nome: "Grell",              vidaMax: 55,  nd: "3"   },
  { nome: "Nothic",             vidaMax: 45,  nd: "2"   },
  { nome: "Otyugh",             vidaMax: 114, nd: "5"   },
  { nome: "Roper",              vidaMax: 93,  nd: "5"   },
  { nome: "Umber Hulk",         vidaMax: 93,  nd: "5"   },
  { nome: "Intellect Devourer", vidaMax: 21,  nd: "2"   },

  // ── DEMÔNIOS & DIABOS ─────────────────────────────────────────────────────
  { nome: "Quasit",             vidaMax: 7,   nd: "1"   },
  { nome: "Dretch",             vidaMax: 18,  nd: "1/4" },
  { nome: "Shadow Demon",       vidaMax: 22,  nd: "4"   },
  { nome: "Manes",              vidaMax: 9,   nd: "1/8" },
  { nome: "Barlgura",           vidaMax: 68,  nd: "5"   },
  { nome: "Chasme",             vidaMax: 84,  nd: "6"   },
  { nome: "Glabrezu",           vidaMax: 157, nd: "9"   },
  { nome: "Hezrou",             vidaMax: 136, nd: "8"   },
  { nome: "Marilith",           vidaMax: 189, nd: "16"  },
  { nome: "Nalfeshnee",         vidaMax: 184, nd: "13"  },
  { nome: "Vrock",              vidaMax: 104, nd: "6"   },
  { nome: "Balor",              vidaMax: 262, nd: "19"  },
  { nome: "Imp",                vidaMax: 10,  nd: "1"   },
  { nome: "Bearded Devil",      vidaMax: 52,  nd: "3"   },
  { nome: "Chain Devil",        vidaMax: 85,  nd: "8"   },
  { nome: "Bone Devil",         vidaMax: 142, nd: "9"   },
  { nome: "Ice Devil",          vidaMax: 180, nd: "14"  },
  { nome: "Pit Fiend",          vidaMax: 300, nd: "20"  },

];