/* ==========================================================================
   COLETÂNEA DE MONSTROS — D&D 5e (Lista Genérica)
   Organizada por categoria. Cada entrada possui:
     nome    → nome do monstro
     vidaMax → HP padrão
     ca      → Classe de Armadura
   ========================================================================== */

const coletaneaMonstros = [

  // ── HUMANOIDES ──────────────────────────────────────────────────────────
  { nome: "Goblin",             vidaMax: 7,   ca: 15 },
  { nome: "Kobold",             vidaMax: 5,   ca: 12 },
  { nome: "Hobgoblin",          vidaMax: 11,  ca: 18 },
  { nome: "Orc",                vidaMax: 15,  ca: 13 },
  { nome: "Gnoll",              vidaMax: 22,  ca: 15 },
  { nome: "Bugbear",            vidaMax: 27,  ca: 16 },
  { nome: "Lizardfolk",         vidaMax: 22,  ca: 15 },
  { nome: "Troglodita",         vidaMax: 13,  ca: 11 },
  { nome: "Bandido",            vidaMax: 11,  ca: 12 },
  { nome: "Capitão Bandido",    vidaMax: 65,  ca: 15 },
  { nome: "Guarda",             vidaMax: 11,  ca: 16 },
  { nome: "Veterano",           vidaMax: 58,  ca: 17 },
  { nome: "Berserker",          vidaMax: 67,  ca: 13 },
  { nome: "Cultista",           vidaMax: 9,   ca: 12 },
  { nome: "Fanático Cultista",  vidaMax: 33,  ca: 13 },

  // ── MORTOS-VIVOS ─────────────────────────────────────────────────────────
  { nome: "Esqueleto",          vidaMax: 13,  ca: 13 },
  { nome: "Zumbi",              vidaMax: 22,  ca: 8  },
  { nome: "Ghoul",              vidaMax: 22,  ca: 12 },
  { nome: "Sombra",             vidaMax: 16,  ca: 12 },
  { nome: "Espectro",           vidaMax: 22,  ca: 12 },
  { nome: "Fantasma",           vidaMax: 45,  ca: 11 },
  { nome: "Múmia",              vidaMax: 58,  ca: 11 },
  { nome: "Senhor Múmia",       vidaMax: 97,  ca: 17 },
  { nome: "Vampiro Spawn",      vidaMax: 82,  ca: 15 },
  { nome: "Vampiro",            vidaMax: 144, ca: 16 },
  { nome: "Lich",               vidaMax: 135, ca: 17 },
  { nome: "Banshee",            vidaMax: 58,  ca: 12 },
  { nome: "Morto-Vivo Carcaça", vidaMax: 45,  ca: 13 },
  { nome: "Wight",              vidaMax: 45,  ca: 14 },
  { nome: "Wraith",             vidaMax: 67,  ca: 13 },

  // ── BESTAS ───────────────────────────────────────────────────────────────
  { nome: "Rato Gigante",       vidaMax: 7,   ca: 12 },
  { nome: "Morcego Gigante",    vidaMax: 22,  ca: 13 },
  { nome: "Aranha Gigante",     vidaMax: 26,  ca: 14 },
  { nome: "Lobo",               vidaMax: 11,  ca: 13 },
  { nome: "Lobo Gigante",       vidaMax: 37,  ca: 13 },
  { nome: "Urso Pardo",         vidaMax: 34,  ca: 11 },
  { nome: "Urso Polar Gigante", vidaMax: 42,  ca: 12 },
  { nome: "Crocodilo",          vidaMax: 19,  ca: 12 },
  { nome: "Crocodilo Gigante",  vidaMax: 85,  ca: 14 },
  { nome: "Escorpião Gigante",  vidaMax: 52,  ca: 15 },
  { nome: "Tubarão Gigante",    vidaMax: 126, ca: 13 },
  { nome: "Pantera",            vidaMax: 13,  ca: 12 },
  { nome: "Tigre",              vidaMax: 37,  ca: 12 },
  { nome: "Leão",               vidaMax: 26,  ca: 12 },
  { nome: "Mamute",             vidaMax: 126, ca: 13 },

  // ── CRIATURAS MÁGICAS & MONSTRUOSIDADES ──────────────────────────────────
  { nome: "Grifo",              vidaMax: 59,  ca: 12 },
  { nome: "Hipogrifo",          vidaMax: 38,  ca: 11 },
  { nome: "Peryton",            vidaMax: 33,  ca: 13 },
  { nome: "Quimera",            vidaMax: 114, ca: 14 },
  { nome: "Basilisco",          vidaMax: 52,  ca: 15 },
  { nome: "Medusa",             vidaMax: 127, ca: 15 },
  { nome: "Minotauro",          vidaMax: 76,  ca: 14 },
  { nome: "Centauro",           vidaMax: 45,  ca: 12 },
  { nome: "Ciclope",            vidaMax: 138, ca: 14 },
  { nome: "Harpia",             vidaMax: 38,  ca: 11 },
  { nome: "Hidra",              vidaMax: 172, ca: 15 },
  { nome: "Mantícora",          vidaMax: 68,  ca: 14 },
  { nome: "Worg",               vidaMax: 26,  ca: 13 },
  { nome: "Troll",              vidaMax: 84,  ca: 15 },
  { nome: "Ogro",               vidaMax: 59,  ca: 11 },
  { nome: "Gigante da Colina",  vidaMax: 105, ca: 13 },
  { nome: "Gigante de Pedra",   vidaMax: 126, ca: 17 },
  { nome: "Gigante do Gelo",    vidaMax: 138, ca: 15 },
  { nome: "Gigante do Fogo",    vidaMax: 162, ca: 18 },
  { nome: "Gigante das Nuvens", vidaMax: 200, ca: 14 },
  { nome: "Gigante da Tempestade", vidaMax: 230, ca: 16 },

  // ── ELEMENTAIS ───────────────────────────────────────────────────────────
  { nome: "Elemental do Ar",    vidaMax: 90,  ca: 15 },
  { nome: "Elemental da Terra", vidaMax: 126, ca: 17 },
  { nome: "Elemental do Fogo",  vidaMax: 102, ca: 13 },
  { nome: "Elemental da Água",  vidaMax: 114, ca: 14 },
  { nome: "Mefito de Lama",     vidaMax: 27,  ca: 11 },
  { nome: "Mefito de Fumaça",   vidaMax: 22,  ca: 12 },
  { nome: "Mefito de Vapor",    vidaMax: 22,  ca: 10 },
  { nome: "Salamandra",         vidaMax: 114, ca: 15 },
  { nome: "Djinn",              vidaMax: 161, ca: 17 },
  { nome: "Efreet",             vidaMax: 200, ca: 17 },

  // ── CONSTRUCTOS ──────────────────────────────────────────────────────────
  { nome: "Homúnculo",          vidaMax: 5,   ca: 13 },
  { nome: "Estátua Animada",    vidaMax: 33,  ca: 17 },
  { nome: "Golem de Argila",    vidaMax: 133, ca: 14 },
  { nome: "Golem de Pedra",     vidaMax: 178, ca: 17 },
  { nome: "Golem de Ferro",     vidaMax: 210, ca: 20 },
  { nome: "Golem de Carne",     vidaMax: 93,  ca: 9  },
  { nome: "Escudo Guardião",    vidaMax: 52,  ca: 17 },

  // ── FERAS DRACÔNICAS ─────────────────────────────────────────────────────
  { nome: "Dragão Filhote Branco",   vidaMax: 32,  ca: 16 },
  { nome: "Dragão Filhote Preto",    vidaMax: 33,  ca: 17 },
  { nome: "Dragão Filhote Verde",    vidaMax: 38,  ca: 17 },
  { nome: "Dragão Filhote Azul",     vidaMax: 52,  ca: 17 },
  { nome: "Dragão Filhote Vermelho", vidaMax: 75,  ca: 17 },
  { nome: "Dragão Jovem Branco",     vidaMax: 133, ca: 17 },
  { nome: "Dragão Jovem Preto",      vidaMax: 127, ca: 18 },
  { nome: "Dragão Jovem Verde",      vidaMax: 136, ca: 18 },
  { nome: "Dragão Jovem Azul",       vidaMax: 152, ca: 18 },
  { nome: "Dragão Jovem Vermelho",   vidaMax: 178, ca: 18 },
  { nome: "Dragão Adulto Branco",    vidaMax: 200, ca: 18 },
  { nome: "Dragão Adulto Preto",     vidaMax: 195, ca: 19 },
  { nome: "Dragão Adulto Verde",     vidaMax: 207, ca: 19 },
  { nome: "Dragão Adulto Azul",      vidaMax: 225, ca: 19 },
  { nome: "Dragão Adulto Vermelho",  vidaMax: 256, ca: 19 },
  { nome: "Dragão Ancião Branco",    vidaMax: 333, ca: 20 },
  { nome: "Dragão Ancião Vermelho",  vidaMax: 546, ca: 22 },
  { nome: "Dragão Ancião Azul",      vidaMax: 481, ca: 22 },
  { nome: "Wyvern",                  vidaMax: 110, ca: 13 },
  { nome: "Pseudodragão",            vidaMax: 7,   ca: 13 },

  // ── ABERRAÇÕES ───────────────────────────────────────────────────────────
  { nome: "Abissal",            vidaMax: 50,  ca: 13 },
  { nome: "Mind Flayer",        vidaMax: 71,  ca: 15 },
  { nome: "Beholder",           vidaMax: 180, ca: 18 },
  { nome: "Beholder Zumbi",     vidaMax: 93,  ca: 15 },
  { nome: "Chuul",              vidaMax: 93,  ca: 16 },
  { nome: "Aboleth",            vidaMax: 135, ca: 17 },
  { nome: "Gibbering Mouther",  vidaMax: 67,  ca: 9  },
  { nome: "Grell",              vidaMax: 55,  ca: 12 },
  { nome: "Nothic",             vidaMax: 45,  ca: 15 },
  { nome: "Otyugh",             vidaMax: 114, ca: 14 },
  { nome: "Roper",              vidaMax: 93,  ca: 20 },
  { nome: "Umber Hulk",         vidaMax: 93,  ca: 18 },
  { nome: "Intellect Devourer", vidaMax: 21,  ca: 12 },

  // ── DEMÔNIOS & DIABOS ─────────────────────────────────────────────────────
  { nome: "Quasit",             vidaMax: 7,   ca: 13 },
  { nome: "Dretch",             vidaMax: 18,  ca: 11 },
  { nome: "Shadow Demon",       vidaMax: 22,  ca: 13 },
  { nome: "Manes",              vidaMax: 9,   ca: 9  },
  { nome: "Barlgura",           vidaMax: 68,  ca: 15 },
  { nome: "Chasme",             vidaMax: 84,  ca: 13 },
  { nome: "Glabrezu",           vidaMax: 157, ca: 17 },
  { nome: "Hezrou",             vidaMax: 136, ca: 16 },
  { nome: "Marilith",           vidaMax: 189, ca: 18 },
  { nome: "Nalfeshnee",         vidaMax: 184, ca: 18 },
  { nome: "Vrock",              vidaMax: 104, ca: 15 },
  { nome: "Balor",              vidaMax: 262, ca: 19 },
  { nome: "Imp",                vidaMax: 10,  ca: 13 },
  { nome: "Bearded Devil",      vidaMax: 52,  ca: 13 },
  { nome: "Chain Devil",        vidaMax: 85,  ca: 16 },
  { nome: "Bone Devil",         vidaMax: 142, ca: 19 },
  { nome: "Ice Devil",          vidaMax: 180, ca: 18 },
  { nome: "Pit Fiend",          vidaMax: 300, ca: 19 },

];